- add weather service class to get city and daily weather
ilyabochkov1331801/Weather-SwiftUI-Combine pull request #9
Opened 2020-12-09 15:17 UTC by AlenNka333

- add endpoints classes to make template for network apis
- add api provider class to make requests
- update swiftgen build scripts, swiftgen.yml file to use localized strings

2020-12-22 07:36 UTC, ilyabochkov1331801 commented on Weather/Weather/Classes/Common/Services/Network/Endpoints/EndpointProtocol.swift
> +protocol EndpointProtocol {
Давай сделаем так, чтобы ендпоинт хранил в себе также тип возвращаемого объекта (AppConvertable), а в APIProvider сразу декодировать его в AppConvertableTarget

2020-12-22 07:36 UTC, ilyabochkov1331801 commented on Weather/Weather/Classes/Common/Services/Weather/WeatherService.swift
> +    private let locationManager = CLLocationManager()
А здесь работу location manager и geo coder обернем в еще один дата менеджер

2020-12-22 07:36 UTC, ilyabochkov1331801 commented on Weather/Weather/Classes/Common/Services/Weather/WeatherServiceProtocol.swift
> +    func getCityInfo(completion: @escaping (Result<String, Error>) -> Void)
Поч здесь через completion, а ниже - AnyPublisher? Давай все через Combine

2020-12-22 07:36 UTC, ilyabochkov1331801 commented on Weather/Weather/Classes/Common/Services/Weather/WeatherService.swift
> +        locationManager.requestWhenInUseAuthorization()
Давай вынесем это в отдельный permissions service и будем хранить их в app state (как в примере)

2020-12-22 07:36 UTC, ilyabochkov1331801 commented on Weather/Weather/Classes/Common/Services/Network/APIProvider.swift
> +    private func performRequest(for endpoint: Endpoint) -> URLRequest? {
давай здесь AnyPublisher

2020-12-22 07:36 UTC, ilyabochkov1331801 commented on Weather/Weather/Classes/Common/Services/Network/APIProvider.swift
> +        guard let request = performRequest(for: endpoint) else {
а здесь используем performRequest в качестве паблишера

2020-12-22 07:36 UTC, ilyabochkov1331801 commented on Weather/Weather/Classes/Common/Services/Weather/WeatherService.swift
> +        guard CLLocationManager.locationServicesEnabled(), let location = location else {
Попробовать здесь начать цепочку операторов от Just(Void) и сделать все через них

2020-12-22 07:36 UTC, ilyabochkov1331801 commented on Weather/Weather/Resources/Localizable/en.lproj/Localizable.strings
> +noLocationPermission_key = "You've denied location authorization.";
Выбрать один вариант стиля нейминга

2020-12-23 19:13 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Weather/WeatherService.swift
> +    private let locationManager = CLLocationManager()
`LocationProvider`, если тут уже начали использовать нейминг с провайдерами

2020-12-23 19:14 UTC, Ikloo commented on Weather/Podfile.lock
> +COCOAPODS: 1.8.4
установите в проекте Bundler, чтобы не возникало таких проблем с зависимостями и после каждого мерджа не приходилось делать под инсталл

2020-12-23 19:43 UTC, Ikloo requested changes

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Network/APIProvider.swift
> +    private func performRequest(for endpoint: Endpoint) -> URLRequest? {
я бы сделал это так: 

```
private extension Endpoint { 
  func asRequest() -> URLRequest? { ... }
}
```

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Network/APIProvider.swift
> +        components.queryItems = endpoint.params.compactMap({ parameter -> URLQueryItem in
`components.queryItems = endpoint.params.compactMap { URLQueryItem(name: $0.key, value: $0.value }`

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Network/APIProvider.swift
> +        return URLRequest(url: url)
return components.url.map { URLRequest(url: url) }

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Network/APIProvider.swift
> +    private func loadData(by request: URLRequest) -> AnyPublisher<Data, Error> {
а это возможно сделал бы так:

```
private extension URLRequest {
  func execute(at session: URLSession = .shared) -> AnyPublisher<Data, Error> {
      session.dataTaskPublisher(for: self)
         .map { $0.data } 
         .eraseToAnyPublisher()
  }
}
```

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Network/APIProvider.swift
> +class APIProvider<Endpoint: EndpointProtocol> {
а посмотрите в сторону Moya, мб понравится, или вы хотите прям селфмейд солюшн?

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Network/APIProvider.swift
> +    func getData(by endpoint: Endpoint) -> AnyPublisher<Data, Error> {
и тогда получится

```
func getData(from endpoint: Endpoint) -> AnyPublisher<Data, Error> {
   endpoint.asRequest?.execute() <- тут можно сделать мап опционала в еррор. Или возвращать URLRequest через комбайн, как ниже Илья написал и прикидывать ошибку оттуда
}
```

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Network/ApiProviderErrors.swift
> +enum ApiProviderErrors: Error {
```
extension APIProvider {
  enum Error: Error, LocalizedError {
     case invalidURL
     
     ....
  }
}
```

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Network/Endpoints/EndpointProtocol.swift
> +protocol EndpointProtocol {
ты не сможешь потом его нормально объявлять как параметр из-за ассоциативного типа(

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Network/Endpoints/WeatherEndpoint.swift
> +            return "/data/2.5" + "/forecast"
`"/data/2.5"` - это версионность? можно засетать сразу в хост, вроде компоненты потом должны скушать

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Network/Endpoints/WeatherEndpoint.swift
> +    var scheme: String {
var scheme: String { "https" }
var host: String { "api.openweathermap.org" }

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Network/Endpoints/WeatherEndpoint.swift
> +    var scheme: String {
я бы это в отдельный экстеншен вынес, таким образом разделил бы

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Network/Endpoints/WeatherEndpoint.swift
> +        switch self {
если key будет использоваться только через отправку параметра, то я бы его хранил внутри этой функции

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Weather/WeatherServiceProtocol.swift
> +    func getCityInfo(completion: @escaping (Result<String, Error>) -> Void)
я бы в ретурн значении указывал бы конкретный тип ошибки

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Classes/Common/Services/Weather/WeatherServiceErrors.swift
> +enum WeatherServiceErrors: Error {
```
extension WeatherService { 
  enum Error { .. }
}
```

2020-12-23 19:43 UTC, Ikloo commented on Weather/Weather/Resources/Localizable/en.lproj/Localizable.strings
> +noLocationPermission_key = "You've denied location authorization.";
согласен с Ильей

2020-12-29 11:10 UTC, ilyabochkov1331801 commented on Weather/Weather/Classes/Common/Services/Network/Endpoints/EndpointProtocol.swift
> +protocol EndpointProtocol {
Сделал)

2020-12-29 11:10 UTC, ilyabochkov1331801 commented on Weather/Weather/Classes/Common/Services/Weather/WeatherServiceProtocol.swift
> +    func getCityInfo(completion: @escaping (Result<String, Error>) -> Void)
До ошибок еще дойдем

2020-12-29 11:26 UTC, ilyabochkov1331801 commented on Weather/Weather/Classes/Common/Services/Network/APIProvider.swift
> +class APIProvider<Endpoint: EndpointProtocol> {
Все сами)

2021-01-04 13:44 UTC, Ikloo approved these changes

2021-01-25 08:45 UTC, merged